import { StuffedHoglin } from "./blocks/StuffedHoglin";
import { FungusColonyComponent } from "./customComponents/blocks/FungusColonyComponent";
import { PropelplantCaneComponent } from "./customComponents/blocks/PropelplantCaneComponent";
import { RichSoulSoilComponent } from "./customComponents/blocks/RichSoulSoilComponent";
import { SoulCompostComonent } from "./customComponents/blocks/SoulCompost";
import { StuffedHoglinComponent } from "./customComponents/blocks/StuffedHoglinComponent";
import { ColoniesComonentRegister } from "./customComponents/items/ColoniesComonent";
import { StuffedHoglinItemComponent } from "./customComponents/items/StuffedHoglinComponent";
import { CookingPotRecipeRegister } from "./registers/CookingPotRecipeRegister";
import { FoodRegister } from "./registers/FoodRegister";
import { LootingRegister } from "./registers/LootRegister";
new PropelplantCaneComponent();
new StuffedHoglinItemComponent();
new StuffedHoglinComponent();
new RichSoulSoilComponent();
new SoulCompostComonent();
new ColoniesComonentRegister();
new FungusColonyComponent();
new StuffedHoglin();
new LootingRegister();
new FoodRegister();
new CookingPotRecipeRegister();
//# sourceMappingURL=main.js.map