import { StuffedHoglin } from "./blocks/StuffedHoglin";
import { FungusColonyComponentComponentRegister } from "./customComponents/blocks/FungusColonyComponent";
import { PropelplantCaneComponentRegister } from "./customComponents/blocks/PropelplantCaneComponent";
import { RichSoulSoilComponentRegister } from "./customComponents/blocks/RichSoulSoilComponent";
import { SoulCompostComonentRegister } from "./customComponents/blocks/SoulCompost";
import { StuffedHoglinBlockComponentRegister } from "./customComponents/blocks/StuffedHoglinComponent";
import { ColoniesComonentRegister } from "./customComponents/items/ColoniesComonent";
import { StuffedHoglinComponentRegister } from "./customComponents/items/StuffedHoglinComponent";
import { CookingPotRecipeRegister } from "./registers/CookingPotRecipeRegister";
import { FoodRegister } from "./registers/FoodRegister";
import { LootingRegister } from "./registers/LootRegister";
new PropelplantCaneComponentRegister();
new StuffedHoglinComponentRegister();
new StuffedHoglinBlockComponentRegister();
new RichSoulSoilComponentRegister();
new SoulCompostComonentRegister();
new ColoniesComonentRegister();
new FungusColonyComponentComponentRegister();
new StuffedHoglin();
new LootingRegister();
new FoodRegister();
new CookingPotRecipeRegister();
//# sourceMappingURL=main.js.map